[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "crispy3"
version = "3.0.0"
description = "A monorepo containing all of the CRISPy-web packages"
authors = [{ name = "Kai Blin", email = "kblin@dtu.dk" }]
readme = "README.md"
license = { text = "AGPL" }
requires-python = ">=3.11"
dependencies = [
    "crispy-models[testing]",
    "crispy-service[testing]",
    "crispy-webapi[testing]",
    "nearmiss[testing]",
    "fakeredis",
    "pytest",
    "pytest-cov",
]

[tool.uv]
package = false

[tool.uv.workspace]
members = [
    "src/api",
    "src/models",
    "src/nearmiss",
    "src/service",
]

[tool.uv.sources]
crispy-models = { workspace = true }
crispy-service = { workspace = true }
crispy-webapi = { workspace = true }
nearmiss = { workspace = true }

[tool.pdm]
distribution = true
