[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "crispy-webapi"
dynamic = ["version"]
authors = [
  { name="SecondaryMetabolites.org packaging team", email="packaging@biosustain.dtu.dk" },
]
description = "A REST-like web API for CRISPy"
readme = "README.md"
license = { text = "GNU Affero General Public License v3 or later (AGPLv3+)" }
requires-python = ">=3"
classifiers = [
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Development Status :: 4 - Beta',
    'Intended Audience :: Science/Research',
    'Topic :: Scientific/Engineering :: Bio-Informatics',
    'License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)',
    'Operating System :: OS Independent',
]
dependencies = [
    "crispy-models",
    "Flask",
    "flask-cors",
    "Jinja2",
    "MarkupSafe",
    "Werkzeug",
    "itsdangerous",
    "valkey",
    "feedparser",
    "gunicorn",
]

[project.urls]
"Homepage" = "https://github.com/secondarymetabolites/crispy-service/"

[project.optional-dependencies]
testing = [
    "fakeredis",
    "pytest",
    "pytest-cov",
    "pytest-flask",
]

[tool.setuptools]
packages = ["crispy_webapi"]

[tool.uv.sources]
crispy-models = { workspace = true }

[tool.setuptools.dynamic]
version = {attr = "crispy_webapi.version.__version__"}
